events {
    worker_connections 1024;
}

http {
    # Importante para que los archivos CSS y JS carguen con el formato correcto
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

   

    server {
        listen 80;

        # 1. Servir el Frontend de React
        location / {
            root /usr/share/nginx/html;
            index index.html;
            # Regla vital para Single Page Applications (SPA) como React.
            # Si el usuario recarga en una ruta como /alertas, Nginx redirige al index.html
            try_files $uri $uri/ /index.html;
        }

       
    }
}