# services/reception/Dockerfile
FROM python:3.10-slim

WORKDIR /app

# Instalar dependencias del sistema necesarias para compilar algunos paquetes
RUN apt-get update && apt-get install -y gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Compilar los contratos proto a Python (Ahora compila ambos)
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. priority.proto
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. geolocation.proto

# Exponer el puerto de FastAPI
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]