# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priority.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'priority.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epriority.proto\x12\x08priority\"P\n\x0c\x41lertRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65mergency_type\x18\x02 \x01(\t\x12\x15\n\rtranscription\x18\x03 \x01(\t\"W\n\x10PriorityResponse\x12\x16\n\x0epriority_level\x18\x01 \x01(\t\x12\x14\n\x0cmatched_rule\x18\x02 \x01(\t\x12\x15\n\rresponse_unit\x18\x03 \x01(\t2Y\n\x12PriorityClassifier\x12\x43\n\rClassifyAlert\x12\x16.priority.AlertRequest\x1a\x1a.priority.PriorityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priority_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERTREQUEST']._serialized_start=28
  _globals['_ALERTREQUEST']._serialized_end=108
  _globals['_PRIORITYRESPONSE']._serialized_start=110
  _globals['_PRIORITYRESPONSE']._serialized_end=197
  _globals['_PRIORITYCLASSIFIER']._serialized_start=199
  _globals['_PRIORITYCLASSIFIER']._serialized_end=288
# @@protoc_insertion_point(module_scope)
