# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import geolocation_pb2 as geolocation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in geolocation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeolocationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessLocation = channel.unary_unary(
                '/geolocation.GeolocationService/ProcessLocation',
                request_serializer=geolocation__pb2.GeoRequest.SerializeToString,
                response_deserializer=geolocation__pb2.GeoResponse.FromString,
                _registered_method=True)


class GeolocationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeolocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessLocation,
                    request_deserializer=geolocation__pb2.GeoRequest.FromString,
                    response_serializer=geolocation__pb2.GeoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geolocation.GeolocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geolocation.GeolocationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeolocationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geolocation.GeolocationService/ProcessLocation',
            geolocation__pb2.GeoRequest.SerializeToString,
            geolocation__pb2.GeoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
