# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geolocation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'geolocation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11geolocation.proto\x12\x0bgeolocation\"&\n\nGeoRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\"e\n\x0bGeoResponse\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\x17\n\x0fzona_geografica\x18\x03 \x01(\t\x12\x11\n\tcuadrante\x18\x04 \x01(\t\x12\x10\n\x08maps_url\x18\x05 \x01(\t2\\\n\x12GeolocationService\x12\x46\n\x0fProcessLocation\x12\x17.geolocation.GeoRequest\x1a\x18.geolocation.GeoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geolocation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOREQUEST']._serialized_start=34
  _globals['_GEOREQUEST']._serialized_end=72
  _globals['_GEORESPONSE']._serialized_start=74
  _globals['_GEORESPONSE']._serialized_end=175
  _globals['_GEOLOCATIONSERVICE']._serialized_start=177
  _globals['_GEOLOCATIONSERVICE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
